### PR TITLE
instrument read_multi and clear

### PR DESCRIPTION
**Pull request by grosser**
@ccocchi 

does that look good ?
If yes I'll do the remaining uninstrumented things.

I was confused because I saw the reads and writes but not the read_multi in my logs and thought my code did not work :)

### CODE REVIEW

**Comment by ccocchi** [comment]
Yes looks good :+1:  I'm not convinced that instrumenting the `clear` was necessary but it's done and I guess it won't hurt. What are the remaining methods you want to instrument?

**Comment by grosser** [comment]
ah yes that was it :D 
I remembered seeing something else but could not find it when reviewing ... please merge :)

**Comment by grosser** [comment]
@ccocchi  good to go ?

**Comment by grosser** [comment]
can you cut a release ?

**Comment by ccocchi** [comment]
0.7.2 is out

**Comment by grosser** [comment]
thx!

**Pull request merged**
