### PR TITLE
ActiveSupport::Cache::Store.instrument is deprecated on rails 4 ... s…

### PR DESCRIPTION
**Pull request by grosser**
…o stop using it

@ccocchi

### CODE REVIEW

**Comment by grosser** [comment]
@dadah89

**Comment by dadah89** [comment]
LGTM 👍 
Somehow tests still ran on 1.9, but tests in all other rubies seem fine...

**Comment by grosser** [comment]
the errors are from that weird github merge commit thing I guess ... we'll see if it's green on merge ...

**Comment by grosser** [comment]
0.9.0

**Pull request merged**
